---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- ( include "labels" . ) | indent 4 }}
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: {{ .Values.applicationPort }}
  selector:
    app.kubernetes.io/name: {{ .Release.Name }}